download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",destfile="household_power_consumption.zip")
data <- read.table(unz("household_power_consumption.zip", "household_power_consumption.txt"), header=T, sep=";",na.string="?")
data$Date <- as.Date(as.character(data$Date),format="%d/%m/%Y")
data$Time <- strptime(paste(data$Date, data$Time),format="%Y-%m-%d %H:%M:%S")
data <- subset(data,Date>='2007-02-01'&Date<='2007-02-02')
png("plot4.png")
par(mfrow = c(2, 2))
plot(data$Time,data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(data$Time,data$Voltage,type="l",,ylab="Voltage",xlab="datetime")
plot(data$Time,data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(x = data$Time, y = data$Sub_metering_2,type="l",col="red")
lines(x = data$Time, y = data$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),xjust=1,bty="n")
plot(data$Time,data$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()