download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",destfile="household_power_consumption.zip")
data <- read.table(unz("household_power_consumption.zip", "household_power_consumption.txt"), header=T, sep=";",na.string="?")
data$Date <- as.Date(as.character(data$Date),format="%d/%m/%Y")
data$Time <- strptime(paste(data$Date, data$Time),format="%Y-%m-%d %H:%M:%S")
data <- subset(data,Date>='2007-02-01'&Date<='2007-02-02')
png("plot1.png")
hist(data$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)",ylab="Frequency")
dev.off()